name: AdventureGameServer
description: a server side of an adventure game.
# version: 1.0.0
# homepage: 127.0.0.1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  route2: ^0.1.1

dev_dependencies:
  pedantic: ^1.9.0
